# Generated by Django 3.0.8 on 2020-07-12 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200712_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last modified'),
            preserve_default=False,
        ),
    ]
